myPokemonAplication/Controllers/LoginController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using myPokemonAplication.Models;

namespace myPokemonAplication.Controllers
{
    public class LoginController : Controller
    {
        private static string LETTERS = "A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z";
        private static string NUMBERS = "0,1,2,3,4,5,6,7,8,9";
        //este archivo cambio
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult LoginAccess(Login thisLogin)
        {
            string[] myLettersArray = LETTERS.Split(',');
            string[] myNumbersArray = NUMBERS.Split(',');

            if (!ModelState.IsValid)
            {
                return View("ErrorLogin");
            }
            var errorpass = thisLogin.Password.ToList();
            
            for (int i = 0; i < 2; i++)
            {
                foreach(string item in myNumbersArray)
                {
                    if (errorpass[i].ToString().ToUpper() == item)
                    {
                        return View("ErrorLogin");
                    }
                }                
            }

            int count = 0;
            bool isNumberOrLetter = false;

            foreach (char item in errorpass)
            {
                foreach(string itemNumber in myNumbersArray)
                {
                    if (item == itemNumber.FirstOrDefault())
                    {
                        isNumberOrLetter = true;
                    }
                }
                foreach (string itemLetter in myLettersArray)
                {
                    if (item.ToString().ToUpper() == itemLetter)
                    {
                        isNumberOrLetter = true;
                    }
                }
                if (!isNumberOrLetter)
                {
                    count++;
                }
                isNumberOrLetter = false;
            }
            if (count != 2)
            {
                return View("ErrorLogin");
            }
            
            int acu = 0;
            for(int i=errorpass.Count()-3;i<errorpass.Count(); i++)
            {
                try
                {
                    if (int.Parse(errorpass[i].ToString()) < 3 || int.Parse(errorpass[i].ToString()) > 8)
                    {
                        return View("ErrorLogin");
                    }
                    acu += int.Parse(errorpass[i].ToString());

                }
                catch(Exception a)
                {
                    return View("ErrorLogin");
                }
            }
            
            return acu<15 ? View("CorrectLogin") : View("ErrorLogin");
        }
        /* asd!!454
         * La contraseña debe tener 3 letras al inicio, 2 caracteres especiales y terminar con 3 numeros
         * entre 3 y 8 que sumados den menos de 15
         */



        public ActionResult LoginAccessComoDeberiaQuedar(Login thisLogin)
        {
           

            if (!ModelState.IsValid)
            {
                return View("ErrorLogin");
            }


            return View("CorrectLogin");
        }
    }
}

myPokemonAplication/Views/Admin/ABMPokemon.cshtml
@using myPokemonAplication.Controllers


@{
    ViewBag.Title = "ABMPokemon";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<body style="background-color: #4F4444">

    <div id="page-content">
        <div class="w3-container">
            <div class="jumbotron ">
                <form class="form-inline">
                    <h2>Administrar Pokemones</h2>
                    <p>Ingresar el nombre del Pokemon</p>
                    <input type="text" class="form-control" size="50" placeholder="Nombre del Pokemon">
                    @*<button type="button" class="btn btn-danger">Agregar</button>*@
                    <button type="button" class="btn btn-danger" onclick="window.location.href = '@Url.Action("AddPokemon", "Admin")'">Add</button>
                    @*<button type="button" class="btn btn-danger">Modificar</button>*@
                    <button type="button" class="btn btn-danger" onclick="window.location.href = '@Url.Action("UpdPokemon", "Admin")'">Modificar</button>
                    <button type="button" class="btn btn-danger" onclick="window.location.href = '@Url.Action("PokemonList", "Admin")'">Listado Pokemon</button>
                    <!-- Modal -->
                    <div class="modal fade" id="myModal" role="dialog">
                        <div class="modal-dialog">
                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title">Under Construction</h4>
                                </div>
                                <div class="modal-body">
                                    <p>Try again later... Sorry :(</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
        </div>
        </div>
    </div>

    <!--///////////////Carousel starts/////////////////-->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">

        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            <li data-target="#myCarousel" data-slide-to="3"></li>
        </ol>
        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox" align="justify">

            <div class="item active">
                <img src="~/Content/Images/Bulbasaur.jpg" alt="Bulbasaur">
                <div class="carousel-caption">
                    @*<h3>#001-Bulbasaur</h3>
                        <p>Type:Leaf</p>*@
                    <div class="container-">
                        <h2>#001</h2>
                        <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo">Bulbasaur</button>
                        @*<button id="myBtn">Try it</button>*@
                        <div id="demo" class="collapse">
                            Type:Leaf
                        </div>

                        @*<button id="myBtn">#001-Bulbasaur</button>
                            <p id="demo"></p>
                            <script>
                                document.getElementById("myBtn").addEventListener("click", function () {
                                    alert('Bulbasaur.jpg');
                                });
                                //function displayDate() {
                                //    document.getElementById("demo").innerHTML = Date();
                                //}

                            </script>*@
                    </div>
                </div>
            </div>

            <div class="item">
                <img src="~/Content/Images/Eevee.jpg" alt="Eevee">
                <div class="carousel-caption">
                    <h3>#133-Eevee</h3>
                    <p>Type:Normal</p>
                </div>
            </div>

            <div class="item">
                <img src="~/Content/Images/Gengar.jpg" alt="Gengar">
                <div class="carousel-caption">
                    <h3>#094-Gengar</h3>
                    <p>Type:Ghost</p>
                </div>
            </div>

            <div class="item">
                <img src="~/Content/Images/Golduck.jpg" alt="Golduck">
                <div class="carousel-caption">
                    <h3>#055-Golduck</h3>
                    <p>Type:Water/Psichic</p>
                </div>
            </div>

        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    @*<div>
        <form>
            <p>

            </p>
            
            <input type="button" class="btn btn-default" value="Go back" onclick="location.href = '@Url.Action("Index", "Login")'" />
        </form>

    </div>*@

    <script>
    $(document).ready(function(){
    // Activate Carousel
    $("#myCarousel").carousel({interval: 500, pause: "hover"});

    // Enable Carousel Indicators
    $(".item1").click(function(){
        $("#myCarousel").carousel(0);
    });
    $(".item2").click(function(){
        $("#myCarousel").carousel(1);
    });
    $(".item3").click(function(){
        $("#myCarousel").carousel(2);
    });
    //$(".item4").click(function(){
    //    $("#myCarousel").carousel(3);
    //});

    // Enable Carousel Controls
    $(".left").click(function(){
        $("#myCarousel").carousel("prev");
    });
    $(".right").click(function(){
        $("#myCarousel").carousel("next");
    });
});
    </script>

</body>

myPokemonAplication/Views/Admin/AddPokemon.cshtml
@model myPokemonAplication.Models.PokemonModel
@{
    ViewBag.Title = "AddPokemon";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    $(document).ready(function() {
        Mod.AddPokemon();
    });
</script>

<body>
   @using (Html.BeginForm())
   {
    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        <div class="form-inline">
            <h1>Add a new Pokemon</h1>
        </div>
        <fieldset>
            <div class="editor-label">
                @Html.LabelFor(x => x.Name)
            </div>
            <div class="editor-field form-group">
                @Html.TextBoxFor(x => x.Name)
            </div>
            <div class="editor-label">
                @Html.LabelFor(x => x.Type)
            </div>
            <div class="editor-field form-group">
                @Html.EnumDropDownListFor(x => x.Type)
            </div>
            <div class="editor-label">
                @Html.LabelFor(x => x.UrlImage)
            </div>
            <div class="editor-field form-group">
               <input type="file" name="file" id="file" style="width: 100%"  accept="image/*" />
                @Html.HiddenFor(x => x.UrlImage, new { id = "UrlImage" })
            </div>
            <div class="editor-label">
                @Html.LabelFor(x => x.PreviousEvolution)
            </div>
            <div class="editor-field form-group">
                @Html.TextBoxFor(x => x.PreviousEvolution)
            </div>
            <div class="editor-label">
                @Html.LabelFor(x => x.NextEvolution)
            </div>
            <div class="editor-field form-group">
                @Html.TextBoxFor(x => x.NextEvolution)
            </div>
            <h1></h1>
            <div>
                <input type="submit" class="btn btn-default" value="Create New Pokemon" />
                <input type="button" class="btn btn-default" value="Reset" onclick="location.href = '@Url.Action("AddPokemon", "Admin")'" />
                <input type="button" class="btn btn-default" id="cancel" value="Cancel" />
            </div>
        </fieldset>
    }
    @*<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="myModalLabel">Modal header</h3>
        </div>
        <div class="modal-body">
            <p>One fine body…</p>
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
            <button class="btn btn-primary">Save changes</button>
        </div>
    </div>*@






</body>

myPokemonAplication/Views/Admin/AddPokemonEmptyFormError.cshtml
@{
    ViewBag.Title = "AddPokemonEmptyFormError";
}

<h2>Error The Form is Empty</h2>
<button type="button" class="btn btn-danger" onclick="window.location.href = '@Url.Action("AddPokemon", "Admin")'">Go back</button>

myPokemonAplication/Views/Admin/CreateNewUser.cshtml
@model myPokemonAplication.Models.UserModel
@{
    ViewBag.Title = "CreateNewUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    $(document).ready(function() {
        Mod2.CreateNewUser();
    });
</script>

<body>
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(false,"",new {@class="text-danger"})
        <div class="form-inline">
            <h2>Create New User</h2>
        </div>
        <fieldset>
            <div class="editor-label">
                @Html.LabelFor(x => x.UserName)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(x => x.UserName)
                @*@Html.ValidationMessageFor(x => x.UserName)*@
            </div>
            <div class="editor-label">
                @Html.LabelFor(x => x.Password)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(x => x.Password)
             @*   @Html.ValidationMessageFor(x => x.Password)*@
            </div>
            <div class="editor-label">
                @Html.LabelFor(x => x.Fname)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(x => x.Fname)
            @*    @Html.ValidationMessageFor(x => x.Fname)*@
            </div>
            <div class="editor-label">
                @Html.LabelFor(x => x.Lname)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(x => x.Lname)
          @*      @Html.ValidationMessageFor(x => x.Lname)*@
            </div>
            <div class="editor-label">
                @Html.LabelFor(x => x.AreaCode)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(x => x.AreaCode)
           @*     @Html.ValidationMessageFor(x => x.AreaCode)*@
            </div>
            <div class="editor-label">
                @Html.LabelFor(x => x.Phone)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(x => x.Phone)
               @* @Html.ValidationMessageFor(x => x.Phone)*@
            </div>
            <div class="editor-label">
                @Html.LabelFor(x => x.BirthDay)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(x => x.BirthDay)
              @*  @Html.ValidationMessageFor(x => x.BirthDay)*@
            </div>
            <div class="editor-label">
                @Html.LabelFor(x => x.Email)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(x => x.Email)
              @*  @Html.ValidationMessageFor(x => x.Email)*@
            </div>
            <div class="editor-label">
                @Html.LabelFor(x => x.TrainerLvl)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(x => x.TrainerLvl)
             @*   @Html.ValidationMessageFor(x => x.TrainerLvl)*@
            </div>
            <h1></h1>
            <div class="btn-group-lg">
                <input type="submit" class="btn btn-default" value="Create New User"/>
                <input type="button" class="btn btn-default" value="Reset" onclick="location.href = '@Url.Action("CreateNewUser", "Admin")'" />
                <input type="button" class="btn btn-default" id="btn_Cancel" value="Cancel" onclick="location.href = '@Url.Action("ABMPokemon", "Admin")'" />
            </div>
        </fieldset>
    }
</body>


@*public string UserName { get; set; }
        public string Password { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public int AreaCode { get; set; }
        public Int64 Phone { get; set; }
        public DateTime BirthDay { get; set; }
        public string Email { get; set; }
        public int TrainerLvl { get; set; }*@

myPokemonAplication/Views/Admin/PokemonList.cshtml
@using System.Activities.Statements
@using myPokemonApp.Model
@model List<myPokemonApp.Model.Pokemon>

<div class="container">
    <h2>Listado Pokemon</h2>
    <p>Este es un listado de todos los pokemones existentes en la base de datos</p>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Pokemon Name</th>
                <th>Pokemon Type</th>
                <th>Url Image</th>
                <th>Previous Evolution</th>
                <th>Next Evolution</th>
            </tr>
        </thead>
        <tbody>
        @foreach (Pokemon item in Model)
        {
            <tr>
                <td>
                    @item.Id
                </td>
                <td>
                    @item.Name
                </td>
                <td>
                    @item.Type
                </td>
                <td>
                    @item.UrlImage
                </td>
                <td>
                    @item.PreviousEvolution
                </td>
                <td>
                    @item.NextEvolution
                </td>
            </tr>
        }
        
        </tbody>
    </table>
</div>

myPokemonAplication/Views/Admin/UpdPokemon.cshtml
@model myPokemonAplication.Models.PokemonModel
@{
    ViewBag.Title = "UpdPokemon";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    $(document).ready(function() {
        Mod3.CreateNewUser();
    });
</script>

<body>
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        <div class="form-inline">
            <h1>Update Pokemon</h1>
        </div>
        <fieldset>
            <div class="editor-label">
                @Html.LabelFor(x => x.Name)
            </div>
            <div class="editor-field form-group">
                @Html.TextBoxFor(x => x.Name)
            </div>
            <div class="editor-label">
                @Html.LabelFor(x => x.Type)
            </div>
            <div class="editor-field form-group">
                @Html.EnumDropDownListFor(x => x.Type)
            </div>
            <div class="editor-label">
                @Html.LabelFor(x => x.UrlImage)
            </div>
            <div class="editor-field form-group">
                <input type="file" name="file" id="file" style="width: 100%" accept="image/*" />
                @Html.HiddenFor(x => x.UrlImage, new { id = "UrlImage" })
            </div>
            <div class="editor-label">
                @Html.LabelFor(x => x.PreviousEvolution)
            </div>
            <div class="editor-field form-group">
                @Html.TextBoxFor(x => x.PreviousEvolution)
            </div>
            <div class="editor-label">
                @Html.LabelFor(x => x.NextEvolution)
            </div>
            <div class="editor-field form-group">
                @Html.TextBoxFor(x => x.NextEvolution)
            </div>
            <h1></h1>
            <div>
                <input type="submit" class="btn btn-default" value="Create New Pokemon" />
                <input type="button" class="btn btn-default" value="Reset" onclick="location.href = '@Url.Action("AddPokemon", "Admin")'" />
                <input type="button" class="btn btn-default" id="btn_Cancel" value="Cancel" />
            </div>
        </fieldset>
    }
    <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="myModalLabel">Modal header</h3>
        </div>
        <div class="modal-body">
            <p>One fine body…</p>
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
            <button class="btn btn-primary">Save changes</button>
        </div>
    </div>






</body>

myPokemonAplication/Views/Admin/UploadImage.cshtml
@{
    ViewBag.Title = "UploadImage";
}


<h2>The image has been succesfully Uploaded</h2>
<button type="button" class="btn btn-danger" onclick="window.location.href = '@Url.Action("AddPokemon", "Admin")'">Go back</button>

myPokemonAplication/Views/Admin/UploadImageError.cshtml
@{
    ViewBag.Title = "UploadImageError";
}

<h2>Error on Upload</h2>
<button type="button" class="btn btn-danger" onclick="window.location.href = '@Url.Action("AddPokemon", "Admin")'">Go back</button>

myPokemonAplication/Views/Admin/UploadImageFileNotSelected.cshtml
@{
    ViewBag.Title = "UploadImageFileNotSelected";
}

<h2>You haven't selected any file</h2>
<button type="button" class="btn btn-danger" onclick="window.location.href = '@Url.Action("AddPokemon", "Admin")'">Go back</button>